"""updated Page model

Revision ID: 5758b3ffd1f9
Revises: ca729a6f5074
Create Date: 2024-12-09 15:55:02.250240

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5758b3ffd1f9"
down_revision: Union[str, None] = "ca729a6f5074"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pages_website_hash_key", "pages", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("pages_website_hash_key", "pages", ["website_hash"])
    # ### end Alembic commands ###
