"""updated Page model

Revision ID: 918c6c5049fa
Revises: 5758b3ffd1f9
Create Date: 2024-12-17 10:03:55.102631

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "918c6c5049fa"
down_revision: Union[str, None] = "5758b3ffd1f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("min_word_length", sa.Integer(), nullable=True))
    op.add_column("pages", sa.Column("mean_word_length", sa.Integer(), nullable=True))
    op.add_column("pages", sa.Column("max_word_length", sa.Integer(), nullable=True))
    op.add_column(
        "pages", sa.Column("min_sentence_length", sa.Integer(), nullable=True)
    )
    op.add_column(
        "pages", sa.Column("mean_sentence_length", sa.Integer(), nullable=True)
    )
    op.add_column(
        "pages", sa.Column("max_sentence_length", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "max_sentence_length")
    op.drop_column("pages", "mean_sentence_length")
    op.drop_column("pages", "min_sentence_length")
    op.drop_column("pages", "max_word_length")
    op.drop_column("pages", "mean_word_length")
    op.drop_column("pages", "min_word_length")
    # ### end Alembic commands ###
