"""update on models

Revision ID: ca729a6f5074
Revises: 7843c0c432b5
Create Date: 2024-12-08 23:47:58.569465

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca729a6f5074"
down_revision: Union[str, None] = "7843c0c432b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pages",
        sa.Column(
            "website_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA256 hash of the website URL",
        ),
    )
    op.alter_column(
        "pages",
        "website",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
        comment="Full URL of the page which was scraped",
        existing_comment="full URL of the page which was scraped",
    )
    op.create_unique_constraint(None, "pages", ["website_hash"])
    op.add_column("targets", sa.Column("finished_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("targets", "finished_at")
    op.drop_constraint(None, "pages", type_="unique")
    op.alter_column(
        "pages",
        "website",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
        comment="full URL of the page which was scraped",
        existing_comment="Full URL of the page which was scraped",
    )
    op.drop_column("pages", "website_hash")
    # ### end Alembic commands ###
